### PR TITLE
removed key members line

### PR DESCRIPTION
**Pull request by possnfiffer**

### CODE REVIEW

**Comment by sgregg85** [comment]
Looks ok to me

**Comment by possnfiffer** [comment]
Why did all those deletions happen? I just edited contributors.md and ran make html
  <li><a href="/pages/about.html">About</a></li>
-                            <li><a href="/pages/code-of-conduct.html">Code of Conduct</a></li>
-                            <li><a href="/pages/contributors.html">Contributors</a></li>
-                            <li><a href="/pages/projects.html">Projects</a></li>
-                            <li><a href="/pages/join-our-slack-team.html">Join our Slack Team</a></li>

**Comment by sgregg85** [comment]
I saw that but when I tested it seemed fine to me. Let's wait for someone else to test and see if it shows up ok for them

**Comment by sgregg85** [comment]
Ok, so I made a clean clone of your forked repo and in addition to the deletions in the nav menu, I get the directory listing for the project's root folder as the main page after running 'make devserver', also the theme does not show at all. I am not sure if it is because you are running OpenBSD as you said and I don't know enough about it to suggest anything but if you do figure out what the issue may be, it might make a good article for the site for any future OpenBSD users.

**Pull request closed without merging**
