### PR TITLE
Add social links

### PR DESCRIPTION
**Pull request by sgregg85**
Implements #25. Added the social media links to pelicanconf.py

### CODE REVIEW

**Comment by kjaymiller** [comment]
great work on this @sgregg85! 

Just a note and I may be wrong on this one. but you usually only want to commit the changes relevant to the PR. You can do so with committing on the one file. 

`git commit <insert file path>`

OR

you can do an interactive commit and only commit the lines necessary
`git commit -p` for _patch_

Since this change has been thoroughly discussed in the chat. I'm cool with it.

**Comment by sgregg85** [comment]
Ill try that next time. I only added pelicanconf.py to the staging area
using 'git add pelicanconf.py' before I did git commit though so I was
surprised when I saw all those changes in the PR. I'm still getting used to
git so I'm thankful when you guys point out something I'm doing wrong.

**Comment by archangelic** [comment]
I think the problem is that you didn't have an up to date master branch before creating your new feature branch. (I could be wrong)

When you are ready to make a new feature branch, you will want to do this on your local repo:

```
git checkout master
git pull
git checkout -b <feature_branch_name_here>
```

**Comment by sgregg85** [comment]
I think you may be right @archangelic. Now that I think about it, I was not going back to master before creating a new branch.

**Comment by sgregg85** [comment]
Going to recreate this branch since I made an error when creating it

**Pull request closed without merging**
